require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const { createClient } = require('@supabase/supabase-js');
const crypto = require('crypto');

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

function contentHash(title, start_datetime, address) {
  return crypto.createHash('md5').update(`${title}${start_datetime}${address}`).digest('hex');
}

// 20 real Chicago venues with accurate coordinates
const events = [
  {
    title: 'Chicago Blues Festival',
    description: 'The world\'s largest free blues festival, held in Millennium Park over three days with dozens of performances across multiple stages.',
    category: ['Music', 'Festivals'],
    start_datetime: '2026-06-05T12:00:00-05:00',
    end_datetime: '2026-06-07T21:00:00-05:00',
    venue_name: 'Millennium Park',
    address: '201 E Randolph St, Chicago, IL 60601',
    city: 'Chicago',
    neighborhood: 'The Loop',
    lat: 41.8827, lng: -87.6233,
    is_free: true,
    official_url: 'https://www.chicago.gov/city/en/depts/dca/supp_info/chicago_blues_festival.html',
    source: 'manual',
  },
  {
    title: 'Green City Market',
    description: 'Chicago\'s premier sustainable farmers market featuring 40+ local vendors selling seasonal produce, meats, dairy, and prepared foods.',
    category: ['Farmers Market', 'Food'],
    start_datetime: '2026-05-02T07:00:00-05:00',
    end_datetime: '2026-05-02T13:00:00-05:00',
    venue_name: 'Lincoln Park',
    address: '1817 N Clark St, Chicago, IL 60614',
    city: 'Chicago',
    neighborhood: 'Lincoln Park',
    lat: 41.9141, lng: -87.6351,
    is_free: true,
    official_url: 'https://www.greencitymarket.org',
    source: 'manual',
    is_recurring: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=SA',
  },
  {
    title: 'Chicago Jazz Festival',
    description: 'Four days of world-class jazz performances at Millennium Park and the Chicago Cultural Center, free and open to the public.',
    category: ['Music', 'Festivals'],
    start_datetime: '2026-08-27T12:00:00-05:00',
    end_datetime: '2026-08-30T21:00:00-05:00',
    venue_name: 'Millennium Park',
    address: '201 E Randolph St, Chicago, IL 60601',
    city: 'Chicago',
    neighborhood: 'The Loop',
    lat: 41.8827, lng: -87.6233,
    is_free: true,
    official_url: 'https://www.chicago.gov/city/en/depts/dca/supp_info/chicago_jazz_festival.html',
    source: 'manual',
  },
  {
    title: 'Taste of Chicago',
    description: 'The world\'s largest food festival featuring 30+ Chicago restaurants, live music, and family activities in Grant Park.',
    category: ['Food', 'Festivals', 'Music'],
    start_datetime: '2026-07-08T11:00:00-05:00',
    end_datetime: '2026-07-12T21:00:00-05:00',
    venue_name: 'Grant Park',
    address: '337 E Randolph St, Chicago, IL 60601',
    city: 'Chicago',
    neighborhood: 'The Loop',
    lat: 41.8791, lng: -87.6205,
    is_free: true,
    price_notes: 'Free entry; food tickets sold separately',
    official_url: 'https://www.chicago.gov/city/en/depts/dca/supp_info/taste_of_chicago.html',
    source: 'manual',
  },
  {
    title: 'Wicker Park Farmers Market',
    description: 'Neighborhood farmers market with fresh produce, artisan goods, and local food vendors every Sunday morning.',
    category: ['Farmers Market', 'Food'],
    start_datetime: '2026-05-03T08:00:00-05:00',
    end_datetime: '2026-05-03T14:00:00-05:00',
    venue_name: 'Wicker Park',
    address: '1425 N Damen Ave, Chicago, IL 60622',
    city: 'Chicago',
    neighborhood: 'Wicker Park',
    lat: 41.9085, lng: -87.6776,
    is_free: true,
    source: 'manual',
    is_recurring: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=SU',
  },
  {
    title: 'Chicago Air and Water Show',
    description: 'North America\'s largest free outdoor air show featuring the U.S. Navy Blue Angels and dozens of aerial performances over Lake Michigan.',
    category: ['Sightseeing', 'Festivals', 'Family-Friendly'],
    start_datetime: '2026-08-15T10:00:00-05:00',
    end_datetime: '2026-08-16T17:00:00-05:00',
    venue_name: 'North Avenue Beach',
    address: '1600 N Lake Shore Dr, Chicago, IL 60613',
    city: 'Chicago',
    neighborhood: 'Lincoln Park',
    lat: 41.9178, lng: -87.6365,
    is_free: true,
    source: 'manual',
  },
  {
    title: 'Randolph Street Market',
    description: 'Chicago\'s largest indoor/outdoor antique and vintage market with 200+ vendors selling furniture, art, clothing, and collectibles.',
    category: ['Sightseeing', 'Arts'],
    start_datetime: '2026-05-30T10:00:00-05:00',
    end_datetime: '2026-05-31T17:00:00-05:00',
    venue_name: 'Plumbers Union Hall',
    address: '1340 W Washington Blvd, Chicago, IL 60607',
    city: 'Chicago',
    neighborhood: 'West Loop',
    lat: 41.8824, lng: -87.6618,
    is_free: false,
    price_min: 10,
    price_max: 10,
    source: 'manual',
  },
  {
    title: 'Chicago SummerDance',
    description: 'Weekly outdoor dance event in Spirit of Music Garden featuring live music and free dance lessons in styles ranging from salsa to swing.',
    category: ['Music', 'Classes', 'Family-Friendly'],
    start_datetime: '2026-06-18T17:30:00-05:00',
    end_datetime: '2026-06-18T21:30:00-05:00',
    venue_name: 'Spirit of Music Garden, Grant Park',
    address: '601 S Michigan Ave, Chicago, IL 60605',
    city: 'Chicago',
    neighborhood: 'The Loop',
    lat: 41.8742, lng: -87.6240,
    is_free: true,
    source: 'manual',
    is_recurring: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=TH,FR,SA',
  },
  {
    title: 'Pitchfork Music Festival',
    description: 'Three-day indie music festival in Union Park featuring three stages, art installations, and a curated food and craft market.',
    category: ['Music', 'Festivals'],
    start_datetime: '2026-07-17T14:00:00-05:00',
    end_datetime: '2026-07-19T22:00:00-05:00',
    venue_name: 'Union Park',
    address: '1501 W Randolph St, Chicago, IL 60607',
    city: 'Chicago',
    neighborhood: 'West Loop',
    lat: 41.8836, lng: -87.6659,
    is_free: false,
    price_min: 75,
    price_max: 165,
    official_url: 'https://pitchfork.com/festival',
    source: 'manual',
  },
  {
    title: 'Art on The Mart',
    description: 'The world\'s largest permanent digital art projection, displayed on the riverwalk-facing facade of The Mart building.',
    category: ['Arts', 'Sightseeing'],
    start_datetime: '2026-05-01T20:00:00-05:00',
    end_datetime: '2026-05-01T23:00:00-05:00',
    venue_name: 'The Mart Riverwalk',
    address: '222 W Merchandise Mart Plaza, Chicago, IL 60654',
    city: 'Chicago',
    neighborhood: 'River North',
    lat: 41.8886, lng: -87.6359,
    is_free: true,
    source: 'manual',
    is_recurring: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=FR,SA,SU',
  },
  {
    title: 'Chicago International Film Festival',
    description: 'The oldest competitive film festival in North America, showcasing 100+ films from around the world over two weeks.',
    category: ['Arts'],
    start_datetime: '2026-10-14T10:00:00-05:00',
    end_datetime: '2026-10-25T22:00:00-05:00',
    venue_name: 'AMC River East 21',
    address: '322 E Illinois St, Chicago, IL 60611',
    city: 'Chicago',
    neighborhood: 'Streeterville',
    lat: 41.8911, lng: -87.6185,
    is_free: false,
    price_min: 18,
    price_max: 30,
    official_url: 'https://www.chicagofilmfestival.com',
    source: 'manual',
  },
  {
    title: 'Lollapalooza',
    description: 'Iconic four-day music festival in Grant Park featuring 170+ artists across 8 stages, plus food, art, and the Kidzapalooza family area.',
    category: ['Music', 'Festivals'],
    start_datetime: '2026-07-30T11:00:00-05:00',
    end_datetime: '2026-08-02T22:00:00-05:00',
    venue_name: 'Grant Park',
    address: '337 E Randolph St, Chicago, IL 60601',
    city: 'Chicago',
    neighborhood: 'The Loop',
    lat: 41.8761, lng: -87.6189,
    is_free: false,
    price_min: 135,
    price_max: 395,
    official_url: 'https://www.lollapalooza.com',
    source: 'manual',
  },
  {
    title: 'Andersonville Midsommarfest',
    description: 'One of Chicago\'s most beloved neighborhood street festivals celebrating Scandinavian heritage with live music, local vendors, and Swedish treats.',
    category: ['Festivals', 'Food', 'Music'],
    start_datetime: '2026-06-06T11:00:00-05:00',
    end_datetime: '2026-06-07T22:00:00-05:00',
    venue_name: 'Clark Street, Andersonville',
    address: '5200 N Clark St, Chicago, IL 60640',
    city: 'Chicago',
    neighborhood: 'Andersonville',
    lat: 41.9765, lng: -87.6683,
    is_free: true,
    source: 'manual',
  },
  {
    title: 'Chicago Architecture Biennial',
    description: 'The largest international architecture and urbanism event in North America, with exhibitions, lectures, and tours across the city.',
    category: ['Arts', 'Sightseeing'],
    start_datetime: '2026-09-19T10:00:00-05:00',
    end_datetime: '2027-01-04T17:00:00-06:00',
    venue_name: 'Chicago Cultural Center',
    address: '78 E Washington St, Chicago, IL 60602',
    city: 'Chicago',
    neighborhood: 'The Loop',
    lat: 41.8832, lng: -87.6248,
    is_free: true,
    official_url: 'https://www.chicagoarchitecturebiennial.org',
    source: 'manual',
  },
  {
    title: 'Hyde Park Jazz Festival',
    description: 'Free two-day jazz festival in Hyde Park featuring local and national artists performing at indoor and outdoor venues across the neighborhood.',
    category: ['Music', 'Festivals'],
    start_datetime: '2026-09-26T12:00:00-05:00',
    end_datetime: '2026-09-27T20:00:00-05:00',
    venue_name: 'Midway Plaisance Park',
    address: '1130 Midway Plaisance N, Chicago, IL 60637',
    city: 'Chicago',
    neighborhood: 'Hyde Park',
    lat: 41.7903, lng: -87.5973,
    is_free: true,
    source: 'manual',
  },
  {
    title: 'Evanston Farmers Market',
    description: 'Award-winning suburban farmers market with 40+ vendors, live music, and cooking demos every Saturday morning.',
    category: ['Farmers Market', 'Food'],
    start_datetime: '2026-05-09T07:30:00-05:00',
    end_datetime: '2026-05-09T13:00:00-05:00',
    venue_name: 'Lot 21 at Church & Oak',
    address: '1817 Church St, Evanston, IL 60201',
    city: 'Evanston',
    neighborhood: 'Downtown Evanston',
    lat: 42.0465, lng: -87.6849,
    is_free: true,
    source: 'manual',
    is_recurring: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=SA',
  },
  {
    title: 'Naperville Last Fling',
    description: 'Labor Day weekend festival in downtown Naperville with national headliner concerts, carnival rides, food vendors, and fireworks.',
    category: ['Festivals', 'Music', 'Family-Friendly'],
    start_datetime: '2026-08-29T12:00:00-05:00',
    end_datetime: '2026-09-01T23:00:00-05:00',
    venue_name: 'Centennial Beach Area',
    address: '500 W Jackson Ave, Naperville, IL 60540',
    city: 'Naperville',
    neighborhood: 'Downtown Naperville',
    lat: 41.7738, lng: -88.1508,
    is_free: false,
    price_min: 5,
    price_max: 20,
    source: 'manual',
  },
  {
    title: 'Chicago Restaurant Week',
    description: 'Two-week culinary event featuring prix-fixe menus at 400+ Chicago restaurants, offering lunch and dinner deals showcasing the city\'s dining scene.',
    category: ['Food'],
    start_datetime: '2026-01-23T11:00:00-06:00',
    end_datetime: '2026-02-05T22:00:00-06:00',
    venue_name: 'Citywide',
    address: 'Various locations, Chicago, IL',
    city: 'Chicago',
    neighborhood: 'Citywide',
    lat: 41.8781, lng: -87.6298,
    is_free: false,
    price_min: 25,
    price_max: 55,
    price_notes: 'Prix-fixe menus at participating restaurants',
    official_url: 'https://www.choosechicago.com/restaurant-week',
    source: 'manual',
  },
  {
    title: 'Haunted Chicago Ghost Tour',
    description: 'Evening walking tour of Chicago\'s most haunted locations in the Loop, led by local historians and storytellers.',
    category: ['Sightseeing', 'Nightlife'],
    start_datetime: '2026-10-03T20:00:00-05:00',
    end_datetime: '2026-10-03T22:30:00-05:00',
    venue_name: 'Chicago Riverwalk (Wabash Bridge)',
    address: '55 N Wabash Ave, Chicago, IL 60602',
    city: 'Chicago',
    neighborhood: 'The Loop',
    lat: 41.8869, lng: -87.6261,
    is_free: false,
    price_min: 28,
    price_max: 28,
    source: 'manual',
    is_recurring: true,
    recurrence_rule: 'FREQ=WEEKLY;BYDAY=FR,SA',
  },
  {
    title: 'Chicago Improv Festival',
    description: 'Ten-day celebration of improvisational comedy featuring local legends and internationally touring improv companies at venues across the city.',
    category: ['Arts', 'Nightlife'],
    start_datetime: '2026-05-13T19:00:00-05:00',
    end_datetime: '2026-05-23T23:00:00-05:00',
    venue_name: 'iO Theater',
    address: '1501 N Kingsbury St, Chicago, IL 60642',
    city: 'Chicago',
    neighborhood: 'Old Town',
    lat: 41.9098, lng: -87.6427,
    is_free: false,
    price_min: 15,
    price_max: 25,
    source: 'manual',
  },
];

async function seed() {
  console.log(`Seeding ${events.length} events...`);
  let inserted = 0;
  let skipped = 0;

  for (const event of events) {
    const { lat, lng, ...rest } = event;

    const row = {
      ...rest,
      submission_status: 'ingested',
      is_user_submitted: false,
      coordinates: `POINT(${lng} ${lat})`,
      content_hash: contentHash(event.title, event.start_datetime, event.address || ''),
    };

    const { error } = await supabase
      .from('events')
      .upsert(row, { onConflict: 'source,external_id', ignoreDuplicates: false });

    if (error) {
      console.error(`  ✗ ${event.title}:`, error.message);
      skipped++;
    } else {
      console.log(`  ✓ ${event.title}`);
      inserted++;
    }
  }

  console.log(`\nDone. ${inserted} inserted/updated, ${skipped} failed.`);
}

seed().catch(console.error);
